name: Docker Image CI

on:
  push:
    branches: [ "main" ]
env: 
      LIBSODIUM_MAKE_ARGS: -j4
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: afkfish
          password: 4ec7647d-bd14-4383-a826-279e407d2b7e
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm/v7
          push: true
          tags: afkfish/worpal:latest
